# Generated by Django 5.0.6 on 2024-11-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='nom_famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille1', models.CharField(blank=True, default='Famille1', max_length=64, null=True, verbose_name='Famille1')),
                ('famille2', models.CharField(blank=True, default='Famille2', max_length=64, null=True, verbose_name='Famille2')),
                ('famille3', models.CharField(blank=True, default='Famille3', max_length=64, null=True, verbose_name='Famille3')),
                ('famille4', models.CharField(blank=True, default='Famille4', max_length=64, null=True, verbose_name='Famille3')),
            ],
            options={
                'verbose_name': 'Objet',
                'verbose_name_plural': 'Objets',
            },
        ),
        migrations.CreateModel(
            name='objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('famille1', models.CharField(blank=True, max_length=64, null=True, verbose_name='Famille1')),
                ('famille2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Famille2')),
                ('famille3', models.CharField(blank=True, max_length=64, null=True, verbose_name='Famille3')),
                ('famille4', models.CharField(blank=True, max_length=64, null=True, verbose_name='Famille3')),
                ('conditions_objet', models.CharField(max_length=200)),
                ('conditions_objet_m2m', models.ManyToManyField(blank=True, to='ressources.condition')),
            ],
            options={
                'verbose_name': 'Objet',
                'verbose_name_plural': 'Objets',
            },
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=64, verbose_name='Prenom')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='Email')),
                ('conditions_utili', models.CharField(max_length=200)),
                ('conditions_utili_m2m', models.ManyToManyField(blank=True, to='ressources.condition')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='resa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.objet', verbose_name='Objet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
