# Generated by Django 5.0.6 on 2024-11-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
